### ISSUE TITLE
Reply not present?

### ISSUE THREAD

**Issue by ScrappyCocco** [edwardslabs/cleverwrap.py#11]
Hi Again,
I'm sorry to be here again, but the problem seems not fixed totally, so before coming i looked a bit in your code, and i edit those lines(87 & 88 - the lines that cause the error):
```
self.time_taken = int(reply.get("time_taken", None))
self.time_elapsed = int(reply.get("time_elapsed", None))
``` 
in:

```
time_taken_var = reply.get("time_taken", None)
time_elapsed_var = reply.get("time_elapsed", None)
try:
     self.time_taken = int(time_taken_var)
     self.time_elapsed = int(time_elapsed_var)
except ValueError:
     print("TIME TAKEN:" + str(time_taken_var))
     print("TIME ELAPSED:" + str(time_elapsed_var))
```

this try-except avoids the old error (ValueError) but then i noticed that when the error happens the clever doesn't give a reply, and return an empty string, this is why i tried:

 ```
while reply == "":
         reply = cw.say(nuovoMessaggio)
         print("Cleverbot Reply:" + reply)
         print("Reply:" + reply)
```
with this little control the error seems to never happens (try to yourself maybe?) so... maybe you should check if there is a reply and, if no, ask the cleverbot again? Something like that?
I'm not sure how your code works so it's just an idea...
Thanks for your support.
Bye

**Comment by edwardslabs** [comment]
Thanks for the feedback I really do appreciate you looking into this and all the information you provided. I will take a look at this and push a new version soon.

**Comment by edwardslabs** [comment]
Okay I think I fixed the issue. In the case where no reply is returned by the API it could be for many different reasons so continuing to request until that has content is not a good idea. I did release a new version that is now on pypi.

Thanks again for your feedback.

**Comment by ScrappyCocco** [comment]
Thank you so much, i will test the new version soon

**Comment by ScrappyCocco** [comment]
I still receive some empty message sometimes, could be an error of mine because i have to check then?
Edit: So leaving the while in my code it's better because i have to check if there is a reply or what kind of error happens?

**Comment by edwardslabs** [comment]
The reply being empty is just an error of the API not something you are doing. I don't want to do a while loop in the class code because it likely still counts as a request and if an actual problem happens where it has to request more than a handful of times you could burn through the free requests very quickly.

The wrapper will throw an exception if the api request returns a non-successful status code so you can assume that when it returns a blank reply that it also counted against your request total.

**Comment by ScrappyCocco** [comment]
Ok then, thank you for the update.
I think that's all for now
